[package]
name = "redisjson"
version = "0.8.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bson = "0.14"
serde_json = "1.0"
libc = "0.2"
jsonpath_lib = { git="https://github.com/gkorland/jsonpath.git", branch="overflow_fix" }
redis-module = { version="0.6.0", features = ["experimental-api"]}
redisearch_api = { git="https://github.com/RediSearch/redisearch-api-rs", branch="del_doc"}
