[package]
name = "redisjson"
version = "0.3.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bson = "0.14"
serde_json = "1.0"
libc = "0.2"
jsonpath_lib = { git="https://github.com/gkorland/jsonpath.git", branch="reaplce_with_ownership_parser" }

[dependencies.redismodule]
git = "https://github.com/redislabsmodules/redismodule-rs.git"
branch = "safe_context_rm_call"
features = ["experimental-api"]

[dependencies.redisearch_api]
git = "https://github.com/RediSearch/redisearch-api-rs.git"
branch = "safe_context_rm_call"
