[package]
name = "redisjson"
version = "0.3.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
libc = "0.2"
jsonpath_lib = "0.2.3"	
redismodule = { git = "https://github.com/RedisLabsModules/redismodule-rs.git", branch = "master" }
